In [ ]:
import numpy

In [ ]:
pip install numpy

In [1]:
import numpy

In [2]:
import numpy as np

In [6]:
a=np.array([1,2,3])

In [7]:
print(a)

[1 2 3]


In [8]:
c=np.array([(1,2,3),(4,5,6)])

In [9]:
print(c)

[[1 2 3]
 [4 5 6]]


In [10]:
trans=np.transpose(c)

In [11]:
print(trans)

[[1 4]
 [2 5]
 [3 6]]


In [12]:
trans.ravel()

array([1, 4, 2, 5, 3, 6])

In [13]:
c.ravel()

array([1, 2, 3, 4, 5, 6])

In [14]:
a.reshape(3,1)

array([[1],
       [2],
       [3]])

In [26]:
ze=np.zeros((3,3))

In [27]:
print(ze)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [24]:
no=np.ones((3,3))

In [25]:
print(no)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [28]:
np.random.random((10,20))

array([[0.29798051, 0.98956945, 0.96449478, 0.48222631, 0.61114593,
        0.84482969, 0.61380974, 0.97361371, 0.08339065, 0.08295449,
        0.61036201, 0.58525572, 0.94241677, 0.69228441, 0.38344335,
        0.60648641, 0.77322647, 0.94135418, 0.54660796, 0.03494547],
       [0.84456084, 0.42808033, 0.05945741, 0.16578911, 0.95039084,
        0.9212633 , 0.38959518, 0.91044097, 0.51642288, 0.12274666,
        0.70967758, 0.27609931, 0.99051303, 0.46147913, 0.15652266,
        0.13788844, 0.70317285, 0.37223567, 0.4512217 , 0.58721485],
       [0.36643762, 0.40495446, 0.13100019, 0.12544505, 0.5177384 ,
        0.42813776, 0.38757257, 0.96953141, 0.15138768, 0.38631356,
        0.84061631, 0.3478202 , 0.0691491 , 0.78683506, 0.94652498,
        0.48569419, 0.44563811, 0.46224133, 0.23323069, 0.94920395],
       [0.68757039, 0.55113155, 0.52100148, 0.49875982, 0.28148711,
        0.98512353, 0.7513928 , 0.33866905, 0.4555704 , 0.81129113,
        0.69551736, 0.36159464, 0.6092623 , 0